// ==UserScript==
// @name         PH - Hangman suggestions
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  it has a fuck huge list
// @author       You
// @match        https://pokeheroes.com/gc_hangman*
// @grant        none
// ==/UserScript==

function pokemonRegexTest(a) {

    var currentHangman = document.querySelector('[style="font-size: 14pt; letter-spacing: 0.5em"]').textContent
    var alreadySubmitted = document.querySelectorAll("[style='opacity: 0.6']")
    var submittedReg = "[^";
    for (var k = 0; k<alreadySubmitted.length; k++) {
        submittedReg = submittedReg.concat(alreadySubmitted[k].textContent.toLowerCase())
    }
    submittedReg = submittedReg.concat("]")
    var unknown = currentHangman.replace(/_/g, submittedReg); //replace underscores with [letters other than currently used] for the regular expression
    unknown = unknown.replace(/\s/g, '\\s'); //replace space with regex whitespace character
    unknown = '^' + unknown + '$' // add ^ (start of string) and $ (end of string) tokens
    var pokemonList = [ //pokemon names -> pokemon items -> pokeHeroes things
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Caterpie",
        "Metapod",
        "Butterfree",
        "Weedle",
        "Kakuna",
        "Beedrill",
        "Pidgey",
        "Pidgeotto",
        "Pidgeot",
        "Rattata",
        "Raticate",
        "Spearow",
        "Fearow",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "Nidoran♀",
        "Nidorina",
        "Nidoqueen",
        "Nidoran♂",
        "Nidorino",
        "Nidoking",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Zubat",
        "Golbat",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Paras",
        "Parasect",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Abra",
        "Kadabra",
        "Alakazam",
        "Machop",
        "Machoke",
        "Machamp",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Ponyta",
        "Rapidash",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Farfetch’d",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Onix",
        "Drowzee",
        "Hypno",
        "Krabby",
        "Kingler",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Cubone",
        "Marowak",
        "Hitmonlee",
        "Hitmonchan",
        "Lickitung",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Tangela",
        "Kangaskhan",
        "Horsea",
        "Seadra",
        "Goldeen",
        "Seaking",
        "Staryu",
        "Starmie",
        "Mr. Mime",
        "Scyther",
        "Jynx",
        "Electabuzz",
        "Magmar",
        "Pinsir",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Omanyte",
        "Omastar",
        "Kabuto",
        "Kabutops",
        "Aerodactyl",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew",
        "Chikorita",
        "Bayleef",
        "Meganium",
        "Cyndaquil",
        "Quilava",
        "Typhlosion",
        "Totodile",
        "Croconaw",
        "Feraligatr",
        "Sentret",
        "Furret",
        "Hoothoot",
        "Noctowl",
        "Ledyba",
        "Ledian",
        "Spinarak",
        "Ariados",
        "Crobat",
        "Chinchou",
        "Lanturn",
        "Pichu",
        "Cleffa",
        "Igglybuff",
        "Togepi",
        "Togetic",
        "Natu",
        "Xatu",
        "Mareep",
        "Flaaffy",
        "Ampharos",
        "Bellossom",
        "Marill",
        "Azumarill",
        "Sudowoodo",
        "Politoed",
        "Hoppip",
        "Skiploom",
        "Jumpluff",
        "Aipom",
        "Sunkern",
        "Sunflora",
        "Yanma",
        "Wooper",
        "Quagsire",
        "Espeon",
        "Umbreon",
        "Murkrow",
        "Slowking",
        "Misdreavus",
        "Unown",
        "Wobbuffet",
        "Girafarig",
        "Pineco",
        "Forretress",
        "Dunsparce",
        "Gligar",
        "Steelix",
        "Snubbull",
        "Granbull",
        "Qwilfish",
        "Scizor",
        "Shuckle",
        "Heracross",
        "Sneasel",
        "Teddiursa",
        "Ursaring",
        "Slugma",
        "Magcargo",
        "Swinub",
        "Piloswine",
        "Corsola",
        "Remoraid",
        "Octillery",
        "Delibird",
        "Mantine",
        "Skarmory",
        "Houndour",
        "Houndoom",
        "Kingdra",
        "Phanpy",
        "Donphan",
        "Porygon2",
        "Stantler",
        "Smeargle",
        "Tyrogue",
        "Hitmontop",
        "Smoochum",
        "Elekid",
        "Magby",
        "Miltank",
        "Blissey",
        "Raikou",
        "Entei",
        "Suicune",
        "Larvitar",
        "Pupitar",
        "Tyranitar",
        "Lugia",
        "Ho-Oh",
        "Celebi",
        "Treecko",
        "Grovyle",
        "Sceptile",
        "Torchic",
        "Combusken",
        "Blaziken",
        "Mudkip",
        "Marshtomp",
        "Swampert",
        "Poochyena",
        "Mightyena",
        "Zigzagoon",
        "Linoone",
        "Wurmple",
        "Silcoon",
        "Beautifly",
        "Cascoon",
        "Dustox",
        "Lotad",
        "Lombre",
        "Ludicolo",
        "Seedot",
        "Nuzleaf",
        "Shiftry",
        "Taillow",
        "Swellow",
        "Wingull",
        "Pelipper",
        "Ralts",
        "Kirlia",
        "Gardevoir",
        "Surskit",
        "Masquerain",
        "Shroomish",
        "Breloom",
        "Slakoth",
        "Vigoroth",
        "Slaking",
        "Nincada",
        "Ninjask",
        "Shedinja",
        "Whismur",
        "Loudred",
        "Exploud",
        "Makuhita",
        "Hariyama",
        "Azurill",
        "Nosepass",
        "Skitty",
        "Delcatty",
        "Sableye",
        "Mawile",
        "Aron",
        "Lairon",
        "Aggron",
        "Meditite",
        "Medicham",
        "Electrike",
        "Manectric",
        "Plusle",
        "Minun",
        "Volbeat",
        "Illumise",
        "Roselia",
        "Gulpin",
        "Swalot",
        "Carvanha",
        "Sharpedo",
        "Wailmer",
        "Wailord",
        "Numel",
        "Camerupt",
        "Torkoal",
        "Spoink",
        "Grumpig",
        "Spinda",
        "Trapinch",
        "Vibrava",
        "Flygon",
        "Cacnea",
        "Cacturne",
        "Swablu",
        "Altaria",
        "Zangoose",
        "Seviper",
        "Lunatone",
        "Solrock",
        "Barboach",
        "Whiscash",
        "Corphish",
        "Crawdaunt",
        "Baltoy",
        "Claydol",
        "Lileep",
        "Cradily",
        "Anorith",
        "Armaldo",
        "Feebas",
        "Milotic",
        "Castform",
        "Kecleon",
        "Shuppet",
        "Banette",
        "Duskull",
        "Dusclops",
        "Tropius",
        "Chimecho",
        "Absol",
        "Wynaut",
        "Snorunt",
        "Glalie",
        "Spheal",
        "Sealeo",
        "Walrein",
        "Clamperl",
        "Huntail",
        "Gorebyss",
        "Relicanth",
        "Luvdisc",
        "Bagon",
        "Shelgon",
        "Salamence",
        "Beldum",
        "Metang",
        "Metagross",
        "Regirock",
        "Regice",
        "Registeel",
        "Latias",
        "Latios",
        "Kyogre",
        "Groudon",
        "Rayquaza",
        "Jirachi",
        "Deoxys",
        "Turtwig",
        "Grotle",
        "Torterra",
        "Chimchar",
        "Monferno",
        "Infernape",
        "Piplup",
        "Prinplup",
        "Empoleon",
        "Starly",
        "Staravia",
        "Staraptor",
        "Bidoof",
        "Bibarel",
        "Kricketot",
        "Kricketune",
        "Shinx",
        "Luxio",
        "Luxray",
        "Budew",
        "Roserade",
        "Cranidos",
        "Rampardos",
        "Shieldon",
        "Bastiodon",
        "Burmy",
        "Wormadam",
        "Mothim",
        "Combee",
        "Vespiquen",
        "Pachirisu",
        "Buizel",
        "Floatzel",
        "Cherubi",
        "Cherrim",
        "Shellos",
        "Gastrodon",
        "Ambipom",
        "Drifloon",
        "Drifblim",
        "Buneary",
        "Lopunny",
        "Mismagius",
        "Honchkrow",
        "Glameow",
        "Purugly",
        "Chingling",
        "Stunky",
        "Skuntank",
        "Bronzor",
        "Bronzong",
        "Bonsly",
        "Mime Jr.",
        "Happiny",
        "Chatot",
        "Spiritomb",
        "Gible",
        "Gabite",
        "Garchomp",
        "Munchlax",
        "Riolu",
        "Lucario",
        "Hippopotas",
        "Hippowdon",
        "Skorupi",
        "Drapion",
        "Croagunk",
        "Toxicroak",
        "Carnivine",
        "Finneon",
        "Lumineon",
        "Mantyke",
        "Snover",
        "Abomasnow",
        "Weavile",
        "Magnezone",
        "Lickilicky",
        "Rhyperior",
        "Tangrowth",
        "Electivire",
        "Magmortar",
        "Togekiss",
        "Yanmega",
        "Leafeon",
        "Glaceon",
        "Gliscor",
        "Mamoswine",
        "Porygon-Z",
        "Gallade",
        "Probopass",
        "Dusknoir",
        "Froslass",
        "Rotom",
        "Uxie",
        "Mesprit",
        "Azelf",
        "Dialga",
        "Palkia",
        "Heatran",
        "Regigigas",
        "Giratina",
        "Cresselia",
        "Phione",
        "Manaphy",
        "Darkrai",
        "Shaymin",
        "Arceus",
        "Victini",
        "Snivy",
        "Servine",
        "Serperior",
        "Tepig",
        "Pignite",
        "Emboar",
        "Oshawott",
        "Dewott",
        "Samurott",
        "Patrat",
        "Watchog",
        "Lillipup",
        "Herdier",
        "Stoutland",
        "Purrloin",
        "Liepard",
        "Pansage",
        "Simisage",
        "Pansear",
        "Simisear",
        "Panpour",
        "Simipour",
        "Munna",
        "Musharna",
        "Pidove",
        "Tranquill",
        "Unfezant",
        "Blitzle",
        "Zebstrika",
        "Roggenrola",
        "Boldore",
        "Gigalith",
        "Woobat",
        "Swoobat",
        "Drilbur",
        "Excadrill",
        "Audino",
        "Timburr",
        "Gurdurr",
        "Conkeldurr",
        "Tympole",
        "Palpitoad",
        "Seismitoad",
        "Throh",
        "Sawk",
        "Sewaddle",
        "Swadloon",
        "Leavanny",
        "Venipede",
        "Whirlipede",
        "Scolipede",
        "Cottonee",
        "Whimsicott",
        "Petilil",
        "Lilligant",
        "Basculin",
        "Sandile",
        "Krokorok",
        "Krookodile",
        "Darumaka",
        "Darmanitan",
        "Maractus",
        "Dwebble",
        "Crustle",
        "Scraggy",
        "Scrafty",
        "Sigilyph",
        "Yamask",
        "Cofagrigus",
        "Tirtouga",
        "Carracosta",
        "Archen",
        "Archeops",
        "Trubbish",
        "Garbodor",
        "Zorua",
        "Zoroark",
        "Minccino",
        "Cinccino",
        "Gothita",
        "Gothorita",
        "Gothitelle",
        "Solosis",
        "Duosion",
        "Reuniclus",
        "Ducklett",
        "Swanna",
        "Vanillite",
        "Vanillish",
        "Vanilluxe",
        "Deerling",
        "Sawsbuck",
        "Emolga",
        "Karrablast",
        "Escavalier",
        "Foongus",
        "Amoonguss",
        "Frillish",
        "Jellicent",
        "Alomomola",
        "Joltik",
        "Galvantula",
        "Ferroseed",
        "Ferrothorn",
        "Klink",
        "Klang",
        "Klinklang",
        "Tynamo",
        "Eelektrik",
        "Eelektross",
        "Elgyem",
        "Beheeyem",
        "Litwick",
        "Lampent",
        "Chandelure",
        "Axew",
        "Fraxure",
        "Haxorus",
        "Cubchoo",
        "Beartic",
        "Cryogonal",
        "Shelmet",
        "Accelgor",
        "Stunfisk",
        "Mienfoo",
        "Mienshao",
        "Druddigon",
        "Golett",
        "Golurk",
        "Pawniard",
        "Bisharp",
        "Bouffalant",
        "Rufflet",
        "Braviary",
        "Vullaby",
        "Mandibuzz",
        "Heatmor",
        "Durant",
        "Deino",
        "Zweilous",
        "Hydreigon",
        "Larvesta",
        "Volcarona",
        "Cobalion",
        "Terrakion",
        "Virizion",
        "Tornadus",
        "Thundurus",
        "Reshiram",
        "Zekrom",
        "Landorus",
        "Kyurem",
        "Keldeo",
        "Meloetta",
        "Genesect",
        "Chespin",
        "Quilladin",
        "Chesnaught",
        "Fennekin",
        "Braixen",
        "Delphox",
        "Froakie",
        "Frogadier",
        "Greninja",
        "Bunnelby",
        "Diggersby",
        "Fletchling",
        "Fletchinder",
        "Talonflame",
        "Scatterbug",
        "Spewpa",
        "Vivillon",
        "Litleo",
        "Pyroar",
        "Flabebe",
        "Floette",
        "Florges",
        "Skiddo",
        "Gogoat",
        "Pancham",
        "Pangoro",
        "Furfrou",
        "Espurr",
        "Meowstic",
        "Honedge",
        "Doublade",
        "Aegislash",
        "Spritzee",
        "Aromatisse",
        "Swirlix",
        "Slurpuff",
        "Inkay",
        "Malamar",
        "Binacle",
        "Barbaracle",
        "Skrelp",
        "Dragalge",
        "Clauncher",
        "Clawitzer",
        "Helioptile",
        "Heliolisk",
        "Tyrunt",
        "Tyrantrum",
        "Amaura",
        "Aurorus",
        "Sylveon",
        "Hawlucha",
        "Dedenne",
        "Carbink",
        "Goomy",
        "Sliggoo",
        "Goodra",
        "Klefki",
        "Phantump",
        "Trevenant",
        "Pumpkaboo",
        "Gourgeist",
        "Bergmite",
        "Avalugg",
        "Noibat",
        "Noivern",
        "Xerneas",
        "Yveltal",
        "Zygarde",
        "Diancie",
        "Hoopa",
        "Volcanion",
        "Rowlet",
        "Dartrix",
        "Decidueye",
        "Litten",
        "Torracat",
        "Incineroar",
        "Popplio",
        "Brionne",
        "Primarina",
        "Pikipek",
        "Trumbeak",
        "Toucannon",
        "Yungoos",
        "Gumshoos",
        "Grubbin",
        "Charjabug",
        "Vikavolt",
        "Crabrawler",
        "Crabominable",
        "Oricorio",
        "Cutiefly",
        "Ribombee",
        "Rockruff",
        "Lycanroc",
        "Wishiwashi",
        "Mareanie",
        "Toxapex",
        "Mudbray",
        "Mudsdale",
        "Dewpider",
        "Araquanid",
        "Fomantis",
        "Lurantis",
        "Morelull",
        "Shiinotic",
        "Salandit",
        "Salazzle",
        "Stufful",
        "Bewear",
        "Bounsweet",
        "Steenee",
        "Tsareena",
        "Comfey",
        "Oranguru",
        "Passimian",
        "Wimpod",
        "Golisopod",
        "Sandygast",
        "Palossand",
        "Pyukumuku",
        "Type: Null",
        "Silvally",
        "Minior",
        "Komala",
        "Turtonator",
        "Togedemaru",
        "Mimikyu",
        "Bruxish",
        "Drampa",
        "Dhelmise",
        "Jangmo-o",
        "Hakamo-o",
        "Kommo-o",
        "Tapu Koko",
        "Tapu Lele",
        "Tapu Bulu",
        "Tapu Fini",
        "Cosmog",
        "Cosmoem",
        "Solgaleo",
        "Lunala",
        "Nihilego",
        "Buzzwole",
        "Pheromosa",
        "Xurkitree",
        "Celesteela",
        "Kartana",
        "Guzzlord",
        "Necrozma",
        "Magearna",
        "Marshadow",
        "Poipole",
        "Naganadel",
        "Stakataka",
        "Blacephalon",
        "Zeraora",
        "Meltan",
        "Melmetal", //end of pokemon names
        "None", //start of pokemon items
        "Master Ball",
        "Ultra Ball",
        "Great Ball",
        "Poké Ball",
        "Safari Ball",
        "Net Ball",
        "Dive Ball",
        "Nest Ball",
        "Repeat Ball",
        "Timer Ball",
        "Luxury Ball",
        "Premier Ball",
        "Dusk Ball",
        "Heal Ball",
        "Quick Ball",
        "Cherish Ball",
        "Potion",
        "Antidote",
        "Burn Heal",
        "Ice Heal",
        "Awakening",
        "Paralyze Heal",
        "Full Restore",
        "Max Potion",
        "Hyper Potion",
        "Super Potion",
        "Full Heal",
        "Revive",
        "Max Revive",
        "Fresh Water",
        "Soda Pop",
        "Lemonade",
        "Moomoo Milk",
        "Energy Powder",
        "Energy Root",
        "Heal Powder",
        "Revival Herb",
        "Ether",
        "Max Ether",
        "Elixir",
        "Max Elixir",
        "Lava Cookie",
        "Berry Juice",
        "Sacred Ash",
        "HP Up",
        "Protein",
        "Iron",
        "Carbos",
        "Calcium",
        "Rare Candy",
        "PP Up",
        "Zinc",
        "PP Max",
        "Old Gateau",
        "Guard Spec.",
        "Dire Hit",
        "X Attack",
        "X Defense",
        "X Speed",
        "X Accuracy",
        "X Sp. Atk",
        "X Sp. Def",
        "Poké Doll",
        "Fluffy Tail",
        "Blue Flute",
        "Yellow Flute",
        "Red Flute",
        "Black Flute",
        "White Flute",
        "Shoal Salt",
        "Shoal Shell",
        "Red Shard",
        "Blue Shard",
        "Yellow Shard",
        "Green Shard",
        "Super Repel",
        "Max Repel",
        "Escape Rope",
        "Repel",
        "Sun Stone",
        "Moon Stone",
        "Fire Stone",
        "Thunder Stone",
        "Water Stone",
        "Leaf Stone",
        "Tiny Mushroom",
        "Big Mushroom",
        "Pearl",
        "Big Pearl",
        "Stardust",
        "Star Piece",
        "Nugget",
        "Heart Scale",
        "Honey",
        "Growth Mulch",
        "Damp Mulch",
        "Stable Mulch",
        "Gooey Mulch",
        "Root Fossil",
        "Claw Fossil",
        "Helix Fossil",
        "Dome Fossil",
        "Old Amber",
        "Armor Fossil",
        "Skull Fossil",
        "Rare Bone",
        "Shiny Stone",
        "Dusk Stone",
        "Dawn Stone",
        "Oval Stone",
        "Odd Keystone",
        "Griseous Orb",
        "Douse Drive",
        "Shock Drive",
        "Burn Drive",
        "Chill Drive",
        "Sweet Heart",
        "Adamant Orb",
        "Lustrous Orb",
        "Greet Mail",
        "Favored Mail",
        "RSVP Mail",
        "Thanks Mail",
        "Inquiry Mail",
        "Like Mail",
        "Reply Mail",
        "Bridge Mail S",
        "Bridge Mail D",
        "Bridge Mail T",
        "Bridge Mail V",
        "Bridge Mail M",
        "Cheri Berry",
        "Chesto Berry",
        "Pecha Berry",
        "Rawst Berry",
        "Aspear Berry",
        "Leppa Berry",
        "Oran Berry",
        "Persim Berry",
        "Lum Berry",
        "Sitrus Berry",
        "Figy Berry",
        "Wiki Berry",
        "Mago Berry",
        "Aguav Berry",
        "Iapapa Berry",
        "Razz Berry",
        "Bluk Berry",
        "Nanab Berry",
        "Wepear Berry",
        "Pinap Berry",
        "Pomeg Berry",
        "Kelpsy Berry",
        "Qualot Berry",
        "Hondew Berry",
        "Grepa Berry",
        "Tamato Berry",
        "Cornn Berry",
        "Magost Berry",
        "Rabuta Berry",
        "Nomel Berry",
        "Spelon Berry",
        "Pamtre Berry",
        "Watmel Berry",
        "Durin Berry",
        "Belue Berry",
        "Occa Berry",
        "Passho Berry",
        "Wacan Berry",
        "Rindo Berry",
        "Yache Berry",
        "Chople Berry",
        "Kebia Berry",
        "Shuca Berry",
        "Coba Berry",
        "Payapa Berry",
        "Tanga Berry",
        "Charti Berry",
        "Kasib Berry",
        "Haban Berry",
        "Colbur Berry",
        "Babiri Berry",
        "Chilan Berry",
        "Liechi Berry",
        "Ganlon Berry",
        "Salac Berry",
        "Petaya Berry",
        "Apicot Berry",
        "Lansat Berry",
        "Starf Berry",
        "Enigma Berry",
        "Micle Berry",
        "Custap Berry",
        "Jaboca Berry",
        "Rowap Berry",
        "Bright Powder",
        "White Herb",
        "Macho Brace",
        "Exp. Share",
        "Quick Claw",
        "Soothe Bell",
        "Mental Herb",
        "Choice Band",
        "King's Rock",
        "Silver Powder",
        "Amulet Coin",
        "Cleanse Tag",
        "Soul Dew",
        "Deep Sea Tooth",
        "Deep Sea Scale",
        "Smoke Ball",
        "Everstone",
        "Focus Band",
        "Lucky Egg",
        "Scope Lens",
        "Metal Coat",
        "Leftovers",
        "Dragon Scale",
        "Light Ball",
        "Soft Sand",
        "Hard Stone",
        "Miracle Seed",
        "Black Glasses",
        "Black Belt",
        "Magnet",
        "Mystic Water",
        "Sharp Beak",
        "Poison Barb",
        "Never-Melt Ice",
        "Spell Tag",
        "Twisted Spoon",
        "Charcoal",
        "Dragon Fang",
        "Silk Scarf",
        "Up-Grade",
        "Shell Bell",
        "Sea Incense",
        "Lax Incense",
        "Lucky Punch",
        "Metal Powder",
        "Thick Club",
        "Stick",
        "Red Scarf",
        "Blue Scarf",
        "Pink Scarf",
        "Green Scarf",
        "Yellow Scarf",
        "Wide Lens",
        "Muscle Band",
        "Wise Glasses",
        "Expert Belt",
        "Light Clay",
        "Life Orb",
        "Power Herb",
        "Toxic Orb",
        "Flame Orb",
        "Quick Powder",
        "Focus Sash",
        "Zoom Lens",
        "Metronome",
        "Iron Ball",
        "Lagging Tail",
        "Destiny Knot",
        "Black Sludge",
        "Icy Rock",
        "Smooth Rock",
        "Heat Rock",
        "Damp Rock",
        "Grip Claw",
        "Choice Scarf",
        "Sticky Barb",
        "Power Bracer",
        "Power Belt",
        "Power Lens",
        "Power Band",
        "Power Anklet",
        "Power Weight",
        "Shed Shell",
        "Big Root",
        "Choice Specs",
        "Flame Plate",
        "Splash Plate",
        "Zap Plate",
        "Meadow Plate",
        "Icicle Plate",
        "Fist Plate",
        "Toxic Plate",
        "Earth Plate",
        "Sky Plate",
        "Mind Plate",
        "Insect Plate",
        "Stone Plate",
        "Spooky Plate",
        "Draco Plate",
        "Dread Plate",
        "Iron Plate",
        "Odd Incense",
        "Rock Incense",
        "Full Incense",
        "Wave Incense",
        "Rose Incense",
        "Luck Incense",
        "Pure Incense",
        "Protector",
        "Electirizer",
        "Magmarizer",
        "Dubious Disc",
        "Reaper Cloth",
        "Razor Claw",
        "Razor Fang",
        "Explorer Kit",
        "Loot Sack",
        "Rule Book",
        "Poké Radar",
        "Point Card",
        "Journal",
        "Seal Case",
        "Fashion Case",
        "Seal Bag",
        "Pal Pad",
        "Works Key",
        "Old Charm",
        "Galactic Key",
        "Red Chain",
        "Town Map",
        "Vs. Seeker",
        "Coin Case",
        "Old Rod",
        "Good Rod",
        "Super Rod",
        "Sprayduck",
        "Poffin Case",
        "Bike",
        "Suite Key",
        "Oak's Letter",
        "Lunar Wing",
        "Member Card",
        "Azure Flute",
        "S.S. Ticket",
        "Contest Pass",
        "Magma Stone",
        "Parcel",
        "Coupon 1",
        "Coupon 2",
        "Coupon 3",
        "Storage Key",
        "Secret Potion",
        "Vs. Recorder",
        "Gracidea",
        "Secret Key",
        "Apricorn Box",
        "Unown Report",
        "Berry Pots",
        "Dowsing Machine",
        "Blue Card",
        "Slowpoke Tail",
        "Clear Bell",
        "Card Key",
        "Basement Key",
        "Squirt Bottle",
        "Red Scale",
        "Lost Item",
        "Pass",
        "Machine Part",
        "Silver Wing",
        "Rainbow Wing",
        "Mystery Egg",
        "Red Apricorn",
        "Blue Apricorn",
        "Yellow Apricorn",
        "Green Apricorn",
        "Pink Apricorn",
        "White Apricorn",
        "Black Apricorn",
        "Fast Ball",
        "Level Ball",
        "Lure Ball",
        "Heavy Ball",
        "Love Ball",
        "Friend Ball",
        "Moon Ball",
        "Sport Ball",
        "Park Ball",
        "Photo Album",
        "GB Sounds",
        "Tidal Bell",
        "Rage Candy Bar",
        "Data Card",
        "Jade Orb",
        "Lock Capsule",
        "Red Orb",
        "Blue Orb",
        "Enigma Stone",
        "Prism Scale",
        "Eviolite",
        "Float Stone",
        "Rocky Helmet",
        "Air Balloon",
        "Red Card",
        "Ring Target",
        "Binding Band",
        "Absorb Bulb",
        "Cell Battery",
        "Eject Button",
        "Fire Gem",
        "Water Gem",
        "Electric Gem",
        "Grass Gem",
        "Ice Gem",
        "Fighting Gem",
        "Poison Gem",
        "Ground Gem",
        "Flying Gem",
        "Psychic Gem",
        "Bug Gem",
        "Rock Gem",
        "Ghost Gem",
        "Dragon Gem",
        "Dark Gem",
        "Steel Gem",
        "Normal Gem",
        "Health Wing",
        "Muscle Wing",
        "Resist Wing",
        "Genius Wing",
        "Clever Wing",
        "Swift Wing",
        "Pretty Wing",
        "Cover Fossil",
        "Plume Fossil",
        "Liberty Pass",
        "Pass Orb",
        "Dream Ball",
        "Poké Toy",
        "Prop Case",
        "Dragon Skull",
        "Balm Mushroom",
        "Big Nugget",
        "Pearl String",
        "Comet Shard",
        "Relic Copper",
        "Relic Silver",
        "Relic Gold",
        "Relic Vase",
        "Relic Band",
        "Relic Statue",
        "Relic Crown",
        "Casteliacone",
        "Dire Hit 2",
        "X Speed 2",
        "X Sp. Atk 2",
        "X Sp. Def 2",
        "X Defense 2",
        "X Attack 2",
        "X Accuracy 2",
        "X Speed 3",
        "X Sp. Atk 3",
        "X Sp. Def 3",
        "X Defense 3",
        "X Attack 3",
        "X Accuracy 3",
        "X Speed 6",
        "X Sp. Atk 6",
        "X Sp. Def 6",
        "X Defense 6",
        "X Attack 6",
        "X Accuracy 6",
        "Ability Urge",
        "Item Drop",
        "Item Urge",
        "Reset Urge",
        "Dire Hit 3",
        "Light Stone",
        "Dark Stone",
        "TM93",
        "TM94",
        "TM95",
        "Xtransceiver",
        "Gram 1",
        "Gram 2",
        "Gram 3",
        "Xtransceiver",
        "Medal Box",
        "DNA Splicers",
        "DNA Splicers",
        "Permit",
        "Oval Charm",
        "Shiny Charm",
        "Plasma Card",
        "Grubby Hanky",
        "Colress Machine",
        "Dropped Item",
        "Dropped Item",
        "Reveal Glass",
        "Weakness Policy",
        "Assault Vest",
        "Holo Caster",
        "Prof's Letter",
        "Roller Skates",
        "Pixie Plate",
        "Ability Capsule",
        "Whipped Dream",
        "Sachet",
        "Luminous Moss",
        "Snowball",
        "Safety Goggles",
        "Poké Flute",
        "Rich Mulch",
        "Surprise Mulch",
        "Boost Mulch",
        "Amaze Mulch",
        "Gengarite",
        "Gardevoirite",
        "Ampharosite",
        "Venusaurite",
        "Charizardite X",
        "Blastoisinite",
        "Mewtwonite X",
        "Mewtwonite Y",
        "Blazikenite",
        "Medichamite",
        "Houndoominite",
        "Aggronite",
        "Banettite",
        "Tyranitarite",
        "Scizorite",
        "Pinsirite",
        "Aerodactylite",
        "Lucarionite",
        "Abomasite",
        "Kangaskhanite",
        "Gyaradosite",
        "Absolite",
        "Charizardite Y",
        "Alakazite",
        "Heracronite",
        "Mawilite",
        "Manectite",
        "Garchompite",
        "Latiasite",
        "Latiosite",
        "Roseli Berry",
        "Kee Berry",
        "Maranga Berry",
        "Sprinklotad",

        "Power Plant Pass",
        "Mega Ring",
        "Intriguing Stone",
        "Common Stone",
        "Discount Coupon",
        "Elevator Key",
        "TMV Pass",
        "Honor of Kalos",
        "Adventure Rules",
        "Strange Souvenir",
        "Lens Case",
        "Makeup Bag",
        "Travel Trunk",
        "Lumiose Galette",
        "Shalour Sable",
        "Jaw Fossil",
        "Sail Fossil",
        "Looker Ticket",
        "Bicycle",
        "Holo Caster",
        "Fairy Gem",
        "Mega Charm",
        "Mega Glove",
        "Mach Bike",
        "Acro Bike",
        "Wailmer Pail",
        "Devon Parts",
        "Soot Sack",
        "Basement Key",
        "Pokéblock Kit",
        "Letter",
        "Eon Ticket",
        "Scanner",
        "Go-Goggles",
        "Meteorite",
        "Storage Key",
        "Devon Scope",
        "S.S. Ticket",
        "HM07",
        "Devon Scuba Gear",
        "Contest Costume",
        "Contest Costume",
        "Magma Suit",
        "Aqua Suit",
        "Pair of Tickets",
        "Mega Bracelet",
        "Mega Pendant",
        "Mega Glasses",
        "Mega Anchor",
        "Mega Stickpin",
        "Mega Tiara",
        "Mega Anklet",
        "Meteorite",
        "Swampertite",
        "Sceptilite",
        "Sablenite",
        "Altarianite",
        "Galladite",
        "Audinite",
        "Metagrossite",
        "Sharpedonite",
        "Slowbronite",
        "Steelixite",
        "Pidgeotite",
        "Glalitite",
        "Diancite",
        "Prison Bottle",
        "Mega Cuff",
        "Cameruptite",
        "Lopunnite",
        "Salamencite",
        "Beedrillite",
        "Meteorite",
        "Meteorite",
        "Key Stone",
        "Meteorite Shard",
        "Eon Flute",
        "Normalium Z",
        "Firium Z",
        "Waterium Z",
        "Electrium Z",
        "Grassium Z",
        "Icium Z",
        "Fightinium Z",
        "Poisonium Z",
        "Groundium Z",
        "Flyinium Z",
        "Psychium Z",
        "Buginium Z",
        "Rockium Z",
        "Ghostium Z",
        "Dragonium Z",
        "Darkinium Z",
        "Steelium Z",
        "Fairium Z",
        "Pikanium Z",
        "Bottle Cap",
        "Gold Bottle Cap",
        "Z-Ring",
        "Decidium Z",
        "Incinium Z",
        "Primarium Z",
        "Tapunium Z",
        "Marshadium Z",
        "Aloraichium Z",
        "Snorlium Z",
        "Eevium Z",
        "Mewnium Z",
        "Normalium Z",
        "Firium Z",
        "Waterium Z",
        "Electrium Z",
        "Grassium Z",
        "Icium Z",
        "Fightinium Z",
        "Poisonium Z",
        "Groundium Z",
        "Flyinium Z",
        "Psychium Z",
        "Buginium Z",
        "Rockium Z",
        "Ghostium Z",
        "Dragonium Z",
        "Darkinium Z",
        "Steelium Z",
        "Fairium Z",
        "Pikanium Z",
        "Decidium Z",
        "Incinium Z",
        "Primarium Z",
        "Tapunium Z",
        "Marshadium Z",
        "Aloraichium Z",
        "Snorlium Z",
        "Eevium Z",
        "Mewnium Z",
        "Pikashunium Z",
        "Pikashunium Z",
        "Forage Bag",
        "Fishing Rod",
        "Professor's Mask",
        "Festival Ticket",
        "Sparkling Stone",
        "Adrenaline Orb",
        "Zygarde Cube",
        "Ice Stone",
        "Ride Pager",
        "Beast Ball",
        "Big Malasada",
        "Red Nectar",
        "Yellow Nectar",
        "Pink Nectar",
        "Purple Nectar",
        "Sun Flute",
        "Moon Flute",
        "Enigmatic Card",
        "Terrain Extender",
        "Protective Pads",
        "Electric Seed",
        "Psychic Seed",
        "Misty Seed",
        "Grassy Seed",
        "Fighting Memory",
        "Flying Memory",
        "Poison Memory",
        "Ground Memory",
        "Rock Memory",
        "Bug Memory",
        "Ghost Memory",
        "Steel Memory",
        "Fire Memory",
        "Water Memory",
        "Grass Memory",
        "Electric Memory",
        "Psychic Memory",
        "Ice Memory",
        "Dragon Memory",
        "Dark Memory",
        "Fairy Memory",
        "Solganium Z",
        "Lunalium Z",
        "Ultranecrozium Z",
        "Mimikium Z",
        "Lycanium Z",
        "Kommonium Z",
        "Solganium Z",
        "Lunalium Z",
        "Ultranecrozium Z",
        "Mimikium Z",
        "Lycanium Z",
        "Kommonium Z",
        "Z-Power Ring",
        "Pink Petal",
        "Orange Petal",
        "Blue Petal",
        "Red Petal",
        "Green Petal",
        "Yellow Petal",
        "Purple Petal",
        "Rainbow Flower",
        "Surge Badge",
        "N-Solarizer",
        "N-Lunarizer",
        "N-Solarizer",
        "N-Lunarizer",
        "Ilima's Normalium Z",
        "Left Poké Ball",
        "Roto Hatch",
        "Roto Bargain",
        "Roto Prize Money",
        "Roto Exp. Points",
        "Roto Friendship",
        "Roto Encounter",
        "Roto Stealth",
        "Roto HP Restore",
        "Roto PP Restore",
        "Roto Boost",
        "Roto Catch", //end of real pokemon items
        //start of pokeheroes event pokemon

        "Applewoodo",
        "Arcaddly",
        "Aurora",
        "Autumn Abra",
        "Autumn Alakazam",
        "Autumn Ampharos",
        "Autumn Flaaffy",
        "Autumn Kadabra",
        "Autumn Mareep",

        "Baby Ducklett",
        "Banettenstein",
        "Baron Fraxure",
        "Beachamp",
        "Blossomly",
        "Buttercream",

        "Candaria",
        "Candy Belly",
        "Catercream",
        "Chocoluv",
        "Clawfa",
        "Clawfairy",
        "Cocktaillon",
        "Combowsken",
        "Cosmoneon",
        "Cottonblu",
        "Crystal Aggron",
        "Crystal Aron",
        "Crystal Lairon",
        "Cubone (Hylian)",
        "Cuddlithe",
        "Cursed Rapidash",

        "Dark Ponyta",
        "Deerling (Easter)",
        "Derpatung",
        "Dirndltank",
        "Disguised Exeggcute",
        "Disguised Exeggutor",
        "Dr. Crazee",
        "Dralucha",
        "Driflamp",

        "Easter Buneary",
        "Easter Bunnelby",
        "Easter Diggersby",
        "Easter Lopunny",
        "Easter Slaking",
        "Easter Slakoth",
        "Easter Vigoroth",

        "Ferrerocoal",
        "Festival Gardevoir",
        "Festival Kirlia",
        "Festival Ralts",
        "Fiesta Larvesta",
        "Fiesta Volcarona",
        "Flabébé (Eternal Flower)",
        "Flabébé (Sakura)",
        "Floette (Eternal Flower)",
        "Floette (Sakura)",
        "Florges (Eternal Flower)",
        "Florges (Sakura)",
        "Flower Boy",
        "Flower Girl",
        "Frosty Kecleon",

        "Gingergoat",
        "Gloweon",
        "Gomaseel",
        "Gooseboarder",
        "Groomicott",

        "Hawaiian Beartic",
        "Hawaiian Cubchoo",
        "Heartomb",
        "Hippopotain",
        "Hippowtain",

        "Ikkakugong",
        "Impasta",
        "J",
        "Jesterig",

        "Keggleon",
        "Kleopard",
        "Knight Axew",

        "Larviprop",
        "Lepreowth",
        "Lightblim",
        "Lillibride",
        "Lord Salamence",
        "Lucario-sensei",
        "Lumiday",

        "Machotide",
        "Magic Ninetales",
        "Maneki Espurr",
        "Maneki Meowstic",
        "Marowak (Hylian)",
        "Mecha Tyranitar",
        "Messenger Fletchinder",
        "Messenger Fletchling",
        "Messenger Talonflame",
        "Metacream",
        "Mikofoo",
        "Mikoshao",
        "Minior",
        "Minun (Flirty)",
        "Mr. Bagon",
        "Mr. Moody",
        "N",
        "Nessy",
        "Nightmare Munna",
        "Nightmare Musharna",
        "Nosepharos",
        "P",
        "Pachirisnow",
        "Perchaun",
        "Pharraloin",
        "Plusle (Flirty)",
        "Polestar",
        "Primal Dialga",
        "Princess Smoochum",
        "Probolight",
        "Prof. Madno",
        "Psyduck (Selfie)",
        "Pumple",
        "Pupibot",

        "Quagschnee",
        "Queen Jynx",

        "Raitoshi",
        "Raylóng",
        "Retro Ducklett",
        "Robin Blaze",
        "Rodeo Scraggy",
        "Rokkyu",
        "Rudolph",

        "Sad and Jolly Jr.",
        "Sala da Menci",
        "Sandcrustle",
        "Sandwebble",
        "Santa Birb",
        "Santa Bird",
        "Satichu",
        "Satochu",
        "Sawsbuck (Easter)",
        "Scattercube",
        "Seatran",
        "Shadow Lugia",
        "Shaysola",
        "Shelcasso",
        "Sheriff Scrafty",
        "Sir Haxelot",
        "Sir Shelgon",
        "Skugar",
        "Slowyore",
        "Snowbuck",
        "Snowling",
        "Solgilyph",
        "Space Spinda",
        "Spewbrella",
        "Spring Ampharos",
        "Spring Flaaffy",
        "Spring Mareep",
        "Sproutlett",
        "Sproutrio",
        "Steamo",
        "Sugar Shock",
        "Summer Ampharos",
        "Summer Flaaffy",
        "Summer Mareep",
        "Super Breloomio",
        "Super Shroom",
        "Surfer Machop",
        "Swampras",

        "Tanghetti",
        "Teddiursa (Misdreavus)",
        "Tendenne",
        "Teslagon",
        "Tom Nook",
        "Toraros",
        "Torcharch",

        "Unown Flake",

        "Valenfloon",
        "Van Bagon",
        "Vivillon (Pride)",

        "Winter Camerupt",
        "Winter Numel",
        "Witch Vulpix",
        "Woopice",
        "Wreafki",

        "Yorebro",
        "Yoreking",

        "Zombeagle",
        "Zomppet",
        "Zweipunk", //end of PH event pokemon
        //pokemon moves
        "Absorb",
        "Accelerock",
        "Acid",
        "Acid Armor",
        "Acid Downpour",
        "Acid Spray",
        "Acrobatics",
        "Acupressure",
        "Aerial Ace",
        "Aeroblast",
        "After You",
        "Agility",
        "Air Cutter",
        "Air Slash",
        "All-Out Pummeling",
        "Ally Switch",
        "Amnesia",
        "Anchor Shot",
        "Ancient Power",
        "Aqua Jet",
        "Aqua Ring",
        "Aqua Tail",
        "Arm Thrust",
        "Aromatherapy",
        "Aromatic Mist",
        "Assist",
        "Assurance",
        "Astonish",
        "Attack Order",
        "Attract",
        "Aura Sphere",
        "Aurora Beam",
        "Aurora Veil",
        "Autotomize",
        "Avalanche",
        "Baby-Doll Eyes",
        "Baddy Bad",
        "Baneful Bunker",
        "Barrage",
        "Barrier",
        "Baton Pass",
        "Beak Blast",
        "Beat Up",
        "Belch",
        "Belly Drum",
        "Bestow",
        "Bide",
        "Bind",
        "Bite",
        "Black Hole Eclipse",
        "Blast Burn",
        "Blaze Kick",
        "Blizzard",
        "Block",
        "Bloom Doom",
        "Blue Flare",
        "Body Slam",
        "Bolt Strike",
        "Bone Club",
        "Bone Rush",
        "Bonemerang",
        "Boomburst",
        "Bounce",
        "Bouncy Bubble",
        "Brave Bird",
        "Breakneck Blitz",
        "Brick Break",
        "Brine",
        "Brutal Swing",
        "Bubble",
        "Bubble Beam",
        "Bug Bite",
        "Bug Buzz",
        "Bulk Up",
        "Bulldoze",
        "Bullet Punch",
        "Bullet Seed",
        "Burn Up",
        "Buzzy Buzz",
        "Calm Mind",
        "Camouflage",
        "Captivate",
        "Catastropika",
        "Celebrate",
        "Charge",
        "Charge Beam",
        "Charm",
        "Chatter",
        "Chip Away",
        "Circle Throw",
        "Clamp",
        "Clanging Scales",
        "Clangorous Soulblaze",
        "Clear Smog",
        "Close Combat",
        "Coil",
        "Comet Punch",
        "Confide",
        "Confuse Ray",
        "Confusion",
        "Constrict",
        "Continental Crush",
        "Conversion",
        "Conversion 2",
        "Copycat",
        "Core Enforcer",
        "Corkscrew Crash",
        "Cosmic Power",
        "Cotton Guard",
        "Cotton Spore",
        "Counter",
        "Covet",
        "Crabhammer",
        "Crafty Shield",
        "Cross Chop",
        "Cross Poison",
        "Crunch",
        "Crush Claw",
        "Crush Grip",
        "Curse",
        "Cut",
        "Dark Pulse",
        "Dark Void",
        "Darkest Lariat",
        "Dazzling Gleam",
        "Defend Order",
        "Defense Curl",
        "Defog",
        "Destiny Bond",
        "Detect",
        "Devastating Drake",
        "Diamond Storm",
        "Dig",
        "Disable",
        "Disarming Voice",
        "Discharge",
        "Dive",
        "Dizzy Punch",
        "Doom Desire",
        "Double Hit",
        "Double Iron Bash",
        "Double Kick",
        "Double Slap",
        "Double Team",
        "Double-Edge",
        "Draco Meteor",
        "Dragon Ascent",
        "Dragon Breath",
        "Dragon Claw",
        "Dragon Dance",
        "Dragon Hammer",
        "Dragon Pulse",
        "Dragon Rage",
        "Dragon Rush",
        "Dragon Tail",
        "Drain Punch",
        "Draining Kiss",
        "Dream Eater",
        "Drill Peck",
        "Drill Run",
        "Dual Chop",
        "Dynamic Punch",
        "Earth Power",
        "Earthquake",
        "Echoed Voice",
        "Eerie Impulse",
        "Egg Bomb",
        "Electric Terrain",
        "Electrify",
        "Electro Ball",
        "Electroweb",
        "Embargo",
        "Ember",
        "Encore",
        "Endeavor",
        "Endure",
        "Energy Ball",
        "Entrainment",
        "Eruption",
        "Explosion",
        "Extrasensory",
        "Extreme Evoboost",
        "Extreme Speed",
        "Facade",
        "Fairy Lock",
        "Fairy Wind",
        "Fake Out",
        "Fake Tears",
        "False Swipe",
        "Feather Dance",
        "Feint",
        "Feint Attack",
        "Fell Stinger",
        "Fiery Dance",
        "Final Gambit",
        "Fire Blast",
        "Fire Fang",
        "Fire Lash",
        "Fire Pledge",
        "Fire Punch",
        "Fire Spin",
        "First Impression",
        "Fissure",
        "Flail",
        "Flame Burst",
        "Flame Charge",
        "Flame Wheel",
        "Flamethrower",
        "Flame Thrower",
        "Flare Blitz",
        "Flash",
        "Flash Cannon",
        "Flatter",
        "Fleur Cannon",
        "Fling",
        "Floaty Fall",
        "Floral Healing",
        "Flower Shield",
        "Fly",
        "Flying Press",
        "Focus Blast",
        "Focus Energy",
        "Focus Punch",
        "Follow Me",
        "Force Palm",
        "Foresight",
        "Forest's Curse",
        "Foul Play",
        "Freeze Shock",
        "Freeze-Dry",
        "Freezy Frost",
        "Frenzy Plant",
        "Frost Breath",
        "Frustration",
        "Fury Attack",
        "Fury Cutter",
        "Fury Swipes",
        "Fusion Bolt",
        "Fusion Flare",
        "Future Sight",
        "Gastro Acid",
        "Gear Grind",
        "Gear Up",
        "Genesis Supernova",
        "Geomancy",
        "Giga Drain",
        "Giga Impact",
        "Gigavolt Havoc",
        "Glaciate",
        "Glare",
        "Glitzy Glow",
        "Grass Knot",
        "Grass Pledge",
        "Grass Whistle",
        "Grassy Terrain",
        "Gravity",
        "Growl",
        "Growth",
        "Grudge",
        "Guard Split",
        "Guard Swap",
        "Guardian of Alola",
        "Guillotine",
        "Gunk Shot",
        "Gust",
        "Gyro Ball",
        "Hail",
        "Hammer Arm",
        "Happy Hour",
        "Harden",
        "Haze",
        "Head Charge",
        "Head Smash",
        "Headbutt",
        "Heal Bell",
        "Heal Block",
        "Heal Order",
        "Heal Pulse",
        "Healing Wish",
        "Heart Stamp",
        "Heart Swap",
        "Heat Crash",
        "Heat Wave",
        "Heavy Slam",
        "Helping Hand",
        "Hex",
        "Hidden Power",
        "High Horsepower",
        "High Jump Kick",
        "Hold Back",
        "Hold Hands",
        "Hone Claws",
        "Horn Attack",
        "Horn Drill",
        "Horn Leech",
        "Howl",
        "Hurricane",
        "Hydro Cannon",
        "Hydro Pump",
        "Hydro Vortex",
        "Hyper Beam",
        "Hyper Fang",
        "Hyper Voice",
        "Hyperspace Fury",
        "Hyperspace Hole",
        "Hypnosis",
        "Ice Ball",
        "Ice Beam",
        "Ice Burn",
        "Ice Fang",
        "Ice Hammer",
        "Ice Punch",
        "Ice Shard",
        "Icicle Crash",
        "Icicle Spear",
        "Icy Wind",
        "Imprison",
        "Incinerate",
        "Inferno",
        "Inferno Overdrive",
        "Infestation",
        "Ingrain",
        "Instruct",
        "Ion Deluge",
        "Iron Defense",
        "Iron Head",
        "Iron Tail",
        "Judgment",
        "Jump Kick",
        "Karate Chop",
        "Kinesis",
        "King's Shield",
        "Knock Off",
        "Land's Wrath",
        "Laser Focus",
        "Last Resort",
        "Lava Plume",
        "Leaf Blade",
        "Leaf Storm",
        "Leaf Tornado",
        "Leafage",
        "Leech Life",
        "Leech Seed",
        "Leer",
        "Let's Snuggle Forever",
        "Lick",
        "Light of Ruin",
        "Light Screen",
        "Light That Burns the Sky",
        "Liquidation",
        "Lock-On",
        "Lovely Kiss",
        "Low Kick",
        "Low Sweep",
        "Lucky Chant",
        "Lunar Dance",
        "Lunge",
        "Luster Purge",
        "Mach Punch",
        "Magic Coat",
        "Magic Room",
        "Magical Leaf",
        "Magma Storm",
        "Magnet Bomb",
        "Magnet Rise",
        "Magnetic Flux",
        "Magnitude",
        "Malicious Moonsault",
        "Mat Block",
        "Me First",
        "Mean Look",
        "Meditate",
        "Mega Drain",
        "Mega Kick",
        "Mega Punch",
        "Megahorn",
        "Memento",
        "Menacing Moonraze Maelstrom",
        "Metal Burst",
        "Metal Claw",
        "Metal Sound",
        "Meteor Mash",
        "Metronome",
        "Milk Drink",
        "Mimic",
        "Mind Blown",
        "Mind Reader",
        "Minimize",
        "Miracle Eye",
        "Mirror Coat",
        "Mirror Move",
        "Mirror Shot",
        "Mist",
        "Mist Ball",
        "Misty Terrain",
        "Moonblast",
        "Moongeist Beam",
        "Moonlight",
        "Morning Sun",
        "Mud Bomb",
        "Mud Shot",
        "Mud Sport",
        "Mud-Slap",
        "Muddy Water",
        "Multi-Attack",
        "Mystical Fire",
        "Nasty Plot",
        "Natural Gift",
        "Nature Power",
        "Nature's Madness",
        "Needle Arm",
        "Never-Ending Nightmare",
        "Night Daze",
        "Night Shade",
        "Night Slash",
        "Nightmare",
        "Noble Roar",
        "Nuzzle",
        "Oblivion Wing",
        "Oceanic Operetta",
        "Octazooka",
        "Odor Sleuth",
        "Ominous Wind",
        "Origin Pulse",
        "Outrage",
        "Overheat",
        "Pain Split",
        "Parabolic Charge",
        "Parting Shot",
        "Pay Day",
        "Payback",
        "Peck",
        "Perish Song",
        "Petal Blizzard",
        "Petal Dance",
        "Phantom Force",
        "Photon Geyser",
        "Pika Papow",
        "Pin Missile",
        "Plasma Fists",
        "Play Nice",
        "Play Rough",
        "Pluck",
        "Poison Fang",
        "Poison Gas",
        "Poison Jab",
        "Poison Powder",
        "Poison Sting",
        "Poison Tail",
        "Pollen Puff",
        "Pound",
        "Powder",
        "Powder Snow",
        "Power Gem",
        "Power Split",
        "Power Swap",
        "Power Trick",
        "Power Trip",
        "Power Whip",
        "Power-Up Punch",
        "Precipice Blades",
        "Present",
        "Prismatic Laser",
        "Protect",
        "Psybeam",
        "Psych Up",
        "Psychic",
        "Psychic Fangs",
        "Psychic Terrain",
        "Psycho Boost",
        "Psycho Cut",
        "Psycho Shift",
        "Psyshock",
        "Psystrike",
        "Psywave",
        "Pulverizing Pancake",
        "Punishment",
        "Purify",
        "Pursuit",
        "Quash",
        "Quick Attack",
        "Quick Guard",
        "Quiver Dance",
        "Rage",
        "Rage Powder",
        "Rain Dance",
        "Rapid Spin",
        "Razor Leaf",
        "Razor Shell",
        "Razor Wind",
        "Recover",
        "Recycle",
        "Reflect",
        "Reflect Type",
        "Refresh",
        "Relic Song",
        "Rest",
        "Retaliate",
        "Return",
        "Revelation Dance",
        "Revenge",
        "Reversal",
        "Roar",
        "Roar of Time",
        "Rock Blast",
        "Rock Climb",
        "Rock Polish",
        "Rock Slide",
        "Rock Smash",
        "Rock Throw",
        "Rock Tomb",
        "Rock Wrecker",
        "Role Play",
        "Rolling Kick",
        "Rollout",
        "Roost",
        "Rototiller",
        "Round",
        "Sacred Fire",
        "Sacred Sword",
        "Safeguard",
        "Sand Attack",
        "Sand Tomb",
        "Sandstorm",
        "Sappy Seed",
        "Savage Spin-Out",
        "Scald",
        "Scary Face",
        "Scratch",
        "Screech",
        "Searing Shot",
        "Searing Sunraze Smash",
        "Secret Power",
        "Secret Sword",
        "Seed Bomb",
        "Seed Flare",
        "Seismic Toss",
        "Self-Destruct",
        "Shadow Ball",
        "Shadow Bone",
        "Shadow Claw",
        "Shadow Force",
        "Shadow Punch",
        "Shadow Sneak",
        "Sharpen",
        "Shattered Psyche",
        "Sheer Cold",
        "Shell Smash",
        "Shell Trap",
        "Shift Gear",
        "Shock Wave",
        "Shore Up",
        "Signal Beam",
        "Silver Wind",
        "Simple Beam",
        "Sing",
        "Sinister Arrow Raid",
        "Sizzly Slide",
        "Sketch",
        "Skill Swap",
        "Skull Bash",
        "Sky Attack",
        "Sky Drop",
        "Sky Uppercut",
        "Slack Off",
        "Slam",
        "Slash",
        "Sleep Powder",
        "Sleep Talk",
        "Sludge",
        "Sludge Bomb",
        "Sludge Wave",
        "Smack Down",
        "Smart Strike",
        "Smelling Salts",
        "Smog",
        "Smokescreen",
        "Snarl",
        "Snatch",
        "Snore",
        "Soak",
        "Soft-Boiled",
        "Solar Beam",
        "Solar Blade",
        "Sonic Boom",
        "Soul-Stealing 7-Star Strike",
        "Spacial Rend",
        "Spark",
        "Sparkling Aria",
        "Sparkly Swirl",
        "Spectral Thief",
        "Speed Swap",
        "Spider Web",
        "Spike Cannon",
        "Spikes",
        "Spiky Shield",
        "Spirit Shackle",
        "Spit Up",
        "Spite",
        "Splash",
        "Splintered Stormshards",
        "Splishy Splash",
        "Spore",
        "Spotlight",
        "Stealth Rock",
        "Steam Eruption",
        "Steamroller",
        "Steel Wing",
        "Sticky Web",
        "Stockpile",
        "Stoked Sparksurfer",
        "Stomp",
        "Stomping Tantrum",
        "Stone Edge",
        "Stored Power",
        "Storm Throw",
        "Strength",
        "Strength Sap",
        "String Shot",
        "Struggle",
        "Struggle Bug",
        "Stun Spore",
        "Submission",
        "Substitute",
        "Subzero Slammer",
        "Sucker Punch",
        "Sunny Day",
        "Sunsteel Strike",
        "Super Fang",
        "Superpower",
        "Supersonic",
        "Supersonic Skystrike",
        "Surf",
        "Swagger",
        "Swallow",
        "Sweet Kiss",
        "Sweet Scent",
        "Swift",
        "Switcheroo",
        "Swords Dance",
        "Synchronoise",
        "Synthesis",
        "Tackle",
        "Tail Glow",
        "Tail Slap",
        "Tail Whip",
        "Tailwind",
        "Take Down",
        "Taunt",
        "Tearful Look",
        "Techno Blast",
        "Tectonic Rage",
        "Teeter Dance",
        "Telekinesis",
        "Teleport",
        "Thief",
        "Thousand Arrows",
        "Thousand Waves",
        "Thrash",
        "Throat Chop",
        "Thunder",
        "Thunder Fang",
        "Thunder Punch",
        "Thunder Shock",
        "Thunder Wave",
        "Thunderbolt",
        "Tickle",
        "Topsy-Turvy",
        "Torment",
        "Toxic",
        "Toxic Spikes",
        "Toxic Thread",
        "Transform",
        "Tri Attack",
        "Trick",
        "Trick Room",
        "Trick-or-Treat",
        "Triple Kick",
        "Trop Kick",
        "Trump Card",
        "Twineedle",
        "Twinkle Tackle",
        "Twister",
        "U-turn",
        "Uproar",
        "V-create",
        "Vacuum Wave",
        "Veevee Volley",
        "Venom Drench",
        "Venoshock",
        "Vice Grip",
        "Vine Whip",
        "Vital Throw",
        "Volt Switch",
        "Volt Tackle",
        "Wake-Up Slap",
        "Water Gun",
        "Water Pledge",
        "Water Pulse",
        "Water Shuriken",
        "Water Sport",
        "Water Spout",
        "Waterfall",
        "Weather Ball",
        "Whirlpool",
        "Whirlwind",
        "Wide Guard",
        "Wild Charge",
        "Will-O-Wisp",
        "Wing Attack",
        "Wish",
        "Withdraw",
        "Wonder Room",
        "Wood Hammer",
        "Work Up",
        "Worry Seed",
        "Wrap",
        "Wring Out",
        "X-Scissor",
        "Yawn",
        "Zap Cannon",
        "Zen Headbutt",
        "Zing Zap",
        "Zippy Zap",
        //towns
        "Accumula Town",
        "Ambrette Town",
        "Anistar City",
        "Anville Town",
        "Aquacorde Town",
        "Aspertia City",
        "Azalea Town",
        "Black City",
        "Blackthorn City",
        "Camphrier Town",
        "Canalave City",
        "Castelia City",
        "Celadon City",
        "Celestic Town",
        "Cerulean City",
        "Cherrygrove City",
        "Cianwood City",
        "Cinnabar Island",
        "Coumarine City",
        "Couriway Town",
        "Cyllage City",
        "Dendemille Town",
        "Dewford Town",
        "Driftveil City",
        "Ecruteak City",
        "Eterna City",
        "Ever Grande City",
        "Fallarbor Town",
        "Fight Area",
        "Five Island",
        "Floaroma Town",
        "Floccesy Town",
        "Fortree City",
        "Four Island",
        "Frontier Access",
        "Fuchsia City",
        "Geosenge Town",
        "Goldenrod City",
        "Hau'oli City",
        "Heahea City",
        "Hearthome City",
        "Humilau City",
        "Icirrus City",
        "Iki Town",
        "Jubilife City",
        "Kiloude City",
        "Konikoni City",
        "Lacunosa Town",
        "Lavaridge Town",
        "Lavender Town",
        "Laverre City",
        "Lentimas Town",
        "Littleroot Town",
        "Lilycove City",
        "Lumiose City",
        "Mahogany Town",
        "Malie City",
        "Mauville City",
        "Mistralton City",
        "Mossdeep City",
        "Nacrene City",
        "New Bark Town",
        "Nimbasa City",
        "Nuvema Town",
        "Oldale Town",
        "Olivine City",
        "One Island",
        "Opelucid City",
        "Oreburgh City",
        "Pacifidlog Town",
        "Pallet Town",
        "Paniola Town",
        "Pastoria City",
        "Petalburg City",
        "Pewter City",
        "Po Town",
        "Resort Area",
        "Rustboro City",
        "Safari Zone Gate",
        "Saffron City",
        "Sandgem Town",
        "Santalune City",
        "Seafolk Village",
        "Seven Island",
        "Shalour City",
        "Six Island",
        "Slateport City",
        "Snowbelle City",
        "Snowpoint City",
        "Solaceon Town",
        "Sootopolis City",
        "Striaton City",
        "Sunyshore City",
        "Survival Area",
        "Tapu Village",
        "Three Island",
        "Twinleaf Town",
        "Two Island",
        "Undella Town",
        "Vaniville Town",
        "Veilstone City",
        "Verdanturf Town",
        "Vermilion City",
        "Violet City",
        "Virbank City",
        "Viridian City",
        "White Forest",
        "Agate Village",
        "Gateon Port",
        "Phenac City",
        "Pyrite Town",
        "The Under",
        "White City",
        "Aqua Resort",
        "Axle Town",
        "Baram Town",
        "Boyleland",
        "Capim Town",
        "Chicole Village",
        "Cocona Village",
        "Easterly Town",
        "Fall City",
        "Haruba Village",
        "Lively Town",
        "Mintale Town",
        "Noe Town",
        "Northerly Town",
        "Pokémon Square",
        "Pueltown",
        "Puzzle Village",
        "Ringtown",
        "Sahra Town",
        "Serene Village",
        "Shaymin Village",
        "Shiver Camp",
        "Summerland",
        "Tilt Village",
        "Toy Town",
        "Treasure Town",
        "Vientown",
        "Westerly Town",
        "Wintown",

        //pokemon people
        "Steven",
        "Gary Oak",
        "Professor Oak",
        "Ash Ketchum",
        "Misty",
        "Brock",
        "Surge",
        "Erika",
        "Sabrina",
        "Koga",
        "Blaine",
        "Giovanni",
        "Lance",
        "Bruno",
        "Lorelei",
        "Agatha",
        "Will",
        "Karen",
        "Sidney",
        "Phoebe",
        "Glacia",
        "Drake",
        "Aaron",
        "Bertha",
        "Flint",
        "Lucian",
        "Shauntal",
        "Marshal",
        "Grimsley",
        "Caitlin",
        "Malva",
        "Siebold",
        "Wikstrom",
        "Drasna",
        "Hala",
        "Olivia",
        "Acerola",
        "Kahili",
        "Molayne",
        "Aaron",
        "Agatha",
        "Allister",
        "Bea",
        "Blaine",
        "Brawly",
        "Brock",
        "Brycen",
        "Bugsy",
        "Burgh",
        "Byron",
        "Candice",
        "Cheren",
        "Chili",
        "Chuck",
        "Cilan",
        "Cissy",
        "Clair",
        "Clay",
        "Clembot",
        "Clemont",
        "Cress",
        "Daisy",
        "Danny",
        "Drake",
        "Drayden",
        "Elesa",
        "Erika",
        "Falkner",
        "Fantina",
        "Flannery",
        "Flint",
        "Forrest",
        "Gardenia",
        "Giovanni",
        "Grant",
        "Iris",
        "James",
        "Janine",
        "Jasmine",
        "Jessie",
        "Juan",
        "Kaz",
        "Kiyo",
        "Koga",
        "Korrina",
        "Lenora",
        "Lily",
        "Lola",
        "Luana",
        "Marlon",
        "Maylene",
        "Miles",
        "Milo",
        "Mr. Moore",
        "Morty",
        "Nessa",
        "Norman",
        "Olympia",
        "Pryce",
        "Ramos",
        "Roark",
        "Roxanne",
        "Roxie",
        "Rudy",
        "Sabrina",
        "The Sensational Sisters",
        "Skyla",
        "Lt Surge",
        "Tate and Liza",
        "Valerie",
        "Viola",
        "Violet",
        "Volkner",
        "Crasher Wake",
        "Walker",
        "Wallace",
        "Wattson",
        "Whitney",
        "Winona",
        "Wulfric",
        "Yas",

        "Champion Alder",
        "Champion Steven",
        "Champion Lance",
        "Champion Wallace",
        "Champion Cynthia",
        "Champion Iris",
        "Champion Diantha",
        "Champion Leon",
        "Champion Red",
        "Champion Blue",
        "Champion Trace",
        "Prof Birch",
        "Prof Oak",
        "Prof Elm",
        "Prof Rowan",
        "Prof Juniper",
        "Prof Sycamore",
        "Prof Kukui",
        "Prof Magnolia",
        "Prof Birch",
        "Professor Oak",
        "Professor Elm",
        "Professor Rowan",
        "Professor Juniper",
        "Professor Sycamore",
        "Professor Kukui",
        "Professor Magnolia",

        "Serena",

        //Misc pokemon related
        "Cosplay Pikachu",
        "Nintendo",
        "Legend",
        "Shiny",
        "Masuda",
        "Team Plasma",
        "Team Rocket",
        "Team Aqua",
        "Team Magma",
        "Team Flare",
        "Team Galactic",
        "Team Skull",
        "Kanto",
        "Johto",
        "Hoenn",
        "Sinnoh",
        "Unova",
        "Kalos",
        "Alola",
        "Red",
        "Blue",
        "Yellow",
        "Ruby",
        "Sapphire",
        "Emerald",
        "Diamond",
        "Pearl",
        "Platinum",
        "Black",
        "White",
        "Sun",
        "Moon",
        "Sword",
        "Shield",
        "Fainted",
        "Poisoned",
        "Paralyzed",
        "Sleep",
        "Asleep",
        "Frozen",
        "Confused",

        "Impish",//natures
        "Hardy",
        "Lonely",
        "Brave",
        "Adamant",
        "Naughty",
        "Bold",
        "Docile",
        "Relaxed",
        "Lax",
        "Timid",
        "Hasty",
        "Serious",
        "Jolly",
        "Naive",
        "Modest",
        "Mild",
        "Quiet",
        "Bashful",
        "Rash",
        "Calm",
        "Gentle",
        "Sassy",
        "Careful",
        "Quirky",
        //abilities
        "Adaptability",
        "Aerilate",
        "Aftermath",
        "Air Lock",
        "Analytic",
        "Anger Point",
        "Anticipation",
        "Arena Trap",
        "Aroma Veil",
        "Aura Break",
        "Bad Dreams",
        "Battle Armor",
        "Big Pecks",
        "Blaze",
        "Bulletproof",
        "Cheek Pouch",
        "Chlorophyll",
        "Clear Body",
        "Cloud Nine",
        "Color Change",
        "Competitive",
        "Compound Eyes",
        "Contrary",
        "Cursed Body",
        "Cute Charm",
        "Damp",
        "Dark Aura",
        "Defeatist",
        "Defiant",
        "Delta Stream",
        "Desolate Land",
        "Download",
        "Drizzle",
        "Drought",
        "Dry Skin",
        "Early Bird",
        "Effect Spore",
        "Fairy Aura",
        "Filter",
        "Flame Body",
        "Flare Boost",
        "Flash Fire",
        "Flower Gift",
        "Flower Veil",
        "Forecast",
        "Forewarn",
        "Friend Guard",
        "Frisk",
        "Fur Coat",
        "Gale Wings",
        "Gluttony",
        "Gooey",
        "Grass Pelt",
        "Guts",
        "Harvest",
        "Healer",
        "Heatproof",
        "Heavy Metal",
        "Honey Gather",
        "Huge Power",
        "Hustle",
        "Hydration",
        "Hyper Cutter",
        "Ice Body",
        "Illuminate",
        "Illusion",
        "Immunity",
        "Imposter",
        "Infiltrator",
        "Inner Focus",
        "Insomnia",
        "Intimidate",
        "Iron Barbs",
        "Iron Fist",
        "Justified",
        "Keen Eye",
        "Klutz",
        "Leaf Guard",
        "Levitate",
        "Light Metal",
        "Lightningrod",
        "Limber",
        "Liquid Ooze",
        "Magic Bounce",
        "Magic Guard",
        "Magician",
        "Magma Armor",
        "Magnet Pull",
        "Marvel Scale",
        "Mega Launcher",
        "Minus",
        "Mold Breaker",
        "Moody",
        "Motor Drive",
        "Moxie",
        "Multiscale",
        "Multitype",
        "Mummy",
        "Natural Cure",
        "No Guard",
        "Normalize",
        "Oblivious",
        "Overcoat",
        "Overgrow",
        "Own Tempo",
        "Parental Bond",
        "Pickpocket",
        "Pickup",
        "Pixilate",
        "Plus",
        "Poison Heal",
        "Poison Point",
        "Poison Touch",
        "Prankster",
        "Pressure",
        "Primordial Sea",
        "Protean",
        "Pure Power",
        "Quick Feet",
        "Rain Dish",
        "Rattled",
        "Reckless",
        "Refrigerate",
        "Regenerator",
        "Rivalry",
        "Rock Head",
        "Rough Skin",
        "Run Away",
        "Sand Force",
        "Sand Rush",
        "Sand Stream",
        "Sand Veil",
        "Sap Sipper",
        "Scrappy",
        "Serene Grace",
        "Shadow Tag",
        "Shed Skin",
        "Sheer Force",
        "Shell Armor",
        "Shield Dust",
        "Simple",
        "Skill Link",
        "Slow Start",
        "Sniper",
        "Snow Cloak",
        "Snow Warning",
        "Solar Power",
        "Solid Rock",
        "Soundproof",
        "Speed Boost",
        "Stall",
        "Stance Change",
        "Static",
        "Steadfast",
        "Stench",
        "Sticky Hold",
        "Storm Drain",
        "Strong Jaw",
        "Sturdy",
        "Suction Cups",
        "Super Luck",
        "Swarm",
        "Sweet Veil",
        "Swift Swim",
        "Symbiosis",
        "Synchronize",
        "Tangled Feet",
        "Technician",
        "Telepathy",
        "Teravolt",
        "Thick Fat",
        "Tinted Lens",
        "Torrent",
        "Tough Claws",
        "Toxic Boost",
        "Trace",
        "Truant",
        "Turboblaze",
        "Unaware",
        "Unburden",
        "Unnerve",
        "Victory Star",
        "Vital Spirit",
        "Volt Absorb",
        "Water Absorb",
        "Water Veil",
        "Weak Armor",
        "White Smoke",
        "Wonder Guard",
        "Wonder Skin",
        "Zen Mode",


        //PokeHeroes

        "Ancient Cave",
        "Auction House",
        "Badges",
        "Battle Shop",
        "Battle team",
        "Battling",
        "Berrygarden",
        "Daycare",
        "Delibird Item Delivery",
        "Dream World Shop",
        "Emera Bank",
        "Emera Beach",
        "Emera Fountain",
        "Emera Square",
        "Event Distribution",
        "Event Shop",
        "Forum",
        "Game Center",
        "Gem Cauldron",
        "Gem Collector",
        "Global Trade Station",
        "Herochat",
        "Honeytree",
        "Hoopa Quest",
        "Item Bag",
        "Item Shop",
        "Lab",
        "Lovemeter",
        "Medal Rally",
        "Newbie Mentoring",
        "Newbie Tutorial",
        "Notifications",
        "Pal Pad",
        "Pokedex",
        "Pokeradar",
        "Polls",
        "Puzzle Collection",
        "Ranklist",
        "Route 53",
        "Royal Tunnel",
        "Rules",
        "Rumbling",
        "Safari Zone",
        "Salon",
        "Shadow Radar",
        "Storage Box",
        "Tall Grass",
        "Union Room",
        "Userprofile",
        "Widgets",
        "Zygarde Quest",
        "Tranerlevel",
        "Mystery Key",

        "Bright Beach",
        "Silent Forest",
        "Windy Prairie",
        "Fiery Furnace",
        "Eternal Tower",
        "Rocky Cave",

        "Mewton M Meowth",
        "Staff",
        "Staid",
        "Explorer Bag",
        "Speed Click",

        //Misc possibly PH related
        "Chef",
        "Playground",
        "Emera Town",
        "Emera Mall",
        "Professor Rowan",
        "Rowan",
        "Enigma Pearl",
        "Clicklist",
        "Royal",
        "Delivery",
        "Gracidea Flower",
        "Pokemon Master",
        "Desolate Land",
        "Users",
        "Castform Cast",
        "Notification",
        "Pokedex",
        "Pokemon",
        "Drenched Bluff",
        "Gem Collector",
        "Auction House",
        "Game Center",
        "Emera Beach",
        "Daycare",
        "Safari Zone",
        "Remakes",
        "Rambo Rumble",
        "Mega Sableye",
        "Yellow Meteorite",
        "Mega Easter Lopunny",
        "Golden Game Chips",
        "Terra Cave",
        "Indigo League",
        "Elite Four",
        "Gym Leader",
        "Pokemon Trainer",
        "Experience",
        "Experience Point",
        "Hangman",
        "Anger Point",
        "Advent Raffle Ticket",
        "Golden Slot",
        "Missingno",
        "Spray Duck",
        "Moomoo Ranch",
        "Black Kyurem",
        "White Kyurem",
        "Forum Thread",
        "Mega Alakazam",
        "Mega Venusaur",
        "Mega Charizard X",
        "Mega Charizard Y",
        "Mega Blastoise",
        "Mega Beedrill",
        "Mega Pidgeot",
        "Mega Alakazam",
        "Mega Slowbro",
        "Mega Gengar",
        "Mega Kangaskhan",
        "Mega Pinsir",
        "Mega Gyarados",
        "Mega Aerodactyl",
        "Mega Mewtwo X",
        "Mega Mewtwo Y",
        "Mega Ampharos",
        "Mega Steelix",
        "Mega Scizor",
        "Mega Heracross",
        "Mega Houndoom",
        "Mega Tyranitar",
        "Mega Sceptile",
        "Mega Blaziken",
        "Mega Swampert",
        "Mega Gardevoir",
        "Mega Sableye",
        "Mega Mawile",
        "Mega Aggron",
        "Mega Medicham",
        "Mega Manectric",
        "Mega Sharpedo",
        "Mega Camerupt",
        "Mega Altaria",
        "Mega Banette",
        "Mega Absol",
        "Mega Glalie",
        "Mega Salamence",
        "Mega Metagross",
        "Mega Latias",
        "Mega Latios",
        "Mega Rayquaza",
        "Mega Lopunny",
        "Mega Garchomp",
        "Mega Lucario",
        "Mega Abomasnow",
        "Mega Gallade",
        "Mega Audino",
        "Mega Diancie",
        "Beach",
        "Pokeheroes Wiki",
        "Lottery",
        "Rival",
        "Auction",
        "Gameboy",
        "Pokemon Master",
        "Pokemon Breeder",
        "Breed",
        "Species",
        "Item",
        "Digimon",
        "Pokeball",
        "Greatball",
        "Ultraball",
        "Masterball",
        "Berrydex",
        "Mission",
        "Easter Hunt",
        "Halloween Sweets",
        "Coinflip",
        "Eggdex",







    ]

    var reg = new RegExp(unknown, "i")
    var possibleAnswers = [];
    console.log(reg)

    for (var i = 0; i<pokemonList.length; i++) {
        var currentCheck = pokemonList[i].match(reg)
        var shouldPush = true
        if (currentCheck != null) { //if it found a match, now check if the match contains letters that have already been used

            for (var x = 0; x<alreadySubmitted.length; x++) {
                var tempBool1 = (currentCheck[0].toLowerCase().includes(alreadySubmitted[x].textContent.toLowerCase())) // does the current match contain the already used letter
                var tempBool2 = (currentHangman.includes(alreadySubmitted[x].textContent) == false) // does the current hangman solution NOT contain the used letter

                if (tempBool1 && tempBool2) {
                    shouldPush = false
                    //console.log(currentCheck[0] + " contains the letter " + alreadySubmitted[x].textContent)
                }
            }

            if (shouldPush) {
                possibleAnswers.push(currentCheck[0])
            }
        }
    }
    if (possibleAnswers.length > 0) {
        document.getElementById("textbar").insertAdjacentHTML("beforeend", "<ul id=answers>campbells chicken noodle possibilities..</ul>")
    }

    for (var j = 0; j<possibleAnswers.length; j++) {
        console.log(possibleAnswers[j])
        document.getElementById("answers").insertAdjacentHTML("beforeend", "<li>" +possibleAnswers[j]+ "</li>")
        if (j > 10) { j += 1000 }
    }
    if (possibleAnswers.length == 0) {
        document.getElementById("textbar").insertAdjacentHTML("beforeend", "<ul id=answers>sorry</ul>")
        document.getElementById("answers").insertAdjacentHTML("beforeend", "<li>idk this one</li>")

    }
    if (currentHangman.includes("STEVEN")) {
        document.getElementById("answers").insertAdjacentHTML("afterbegin", '<iframe width="560" height="315" src="https://www.youtube.com/embed/j-K-zqLNtcw?start=10&autoplay=1&controls=0" frameborder="1" autoplay="1" allow="picture-in-picture" allowfullscreen></iframe>')
        var stevensHeadlines = document.getElementsByClassName("headline1")
        var stevensSidebar = document.getElementsByClassName("sidebar")
        var stevensNormaltext = document.getElementsByClassName("normaltext")

        for (var s = 0; s<stevensHeadlines.length; s++) {
            stevensHeadlines[s].textContent = "Steven's Penis"
        }
        for (var t = 0; t<stevensSidebar.length; t++) {
            stevensSidebar[t].firstChild.lastChild.textContent = "Steven's Penis"
        }

        stevensNormaltext[0].innerText = "The Steven game randomly selects a Steven-/Steven's Penis-related word for you and you have to guess it step by step. Decide wisely and click on a penis to choose it. You can only make five wrong guesses per round. After winning a round, you receive an amount of Stevens Penises which is based on your solved Steven in a row stat and on the difficulty of the penis."
        document.querySelector('[style="font-size: 14pt; letter-spacing: 0.5em"]').textContent += "'S PENIS"
        document.getElementsByClassName("gameChipsLeft")[0].nextSibling.textContent = " Penises (Steven's)"

        function addGlobalStyle(css) {
            var head, style;
            head = document.getElementsByTagName('head')[0];
            if (!head) { return; }
            style = document.createElement('style');
            style.type = 'text/css';
            style.innerHTML = css;
            head.appendChild(style);
        }
        addGlobalStyle('body {font-family: CURSIVE; font-size: 13px;}');
    }
}

pokemonRegexTest()


